//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosapi.ElCosapino.UI.AdminAdmin.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cosapi.ElCosapino.UI.AdminAdmin.Views.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLabel {
            get {
                return ResourceManager.GetString("EnglishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Combinada.
        /// </summary>
        public static string EtiquetaActividadCombinada {
            get {
                return ResourceManager.GetString("EtiquetaActividadCombinada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Crítica.
        /// </summary>
        public static string EtiquetaActividadCritica {
            get {
                return ResourceManager.GetString("EtiquetaActividadCritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Combinadas.
        /// </summary>
        public static string EtiquetaActividadesCombinadas {
            get {
                return ResourceManager.GetString("EtiquetaActividadesCombinadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Críticas.
        /// </summary>
        public static string EtiquetaActividadesCriticas {
            get {
                return ResourceManager.GetString("EtiquetaActividadesCriticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Criticas por Empresa.
        /// </summary>
        public static string EtiquetaActividadesCriticasPorEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaActividadesCriticasPorEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Combinadas por Aprobar.
        /// </summary>
        public static string EtiquetaApruebaActividadesCombinadas {
            get {
                return ResourceManager.GetString("EtiquetaApruebaActividadesCombinadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Críticas por Aprobar.
        /// </summary>
        public static string EtiquetaApruebaActividadesCriticas {
            get {
                return ResourceManager.GetString("EtiquetaApruebaActividadesCriticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Maestras por Aprobar.
        /// </summary>
        public static string EtiquetaApruebaActividadesMaestras {
            get {
                return ResourceManager.GetString("EtiquetaApruebaActividadesMaestras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Transacciones.
        /// </summary>
        public static string etiquetaCantidadTransacciones {
            get {
                return ResourceManager.GetString("etiquetaCantidadTransacciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string EtiquetaCerrar {
            get {
                return ResourceManager.GetString("EtiquetaCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre Contable.
        /// </summary>
        public static string EtiquetaCierreContable {
            get {
                return ResourceManager.GetString("EtiquetaCierreContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación.
        /// </summary>
        public static string etiquetaClasificacion {
            get {
                return ResourceManager.GetString("etiquetaClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        public static string EtiquetaClave {
            get {
                return ResourceManager.GetString("EtiquetaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Actividad Crítica.
        /// </summary>
        public static string EtiquetaCodigoActivCritica {
            get {
                return ResourceManager.GetString("EtiquetaCodigoActivCritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Actividad.
        /// </summary>
        public static string EtiquetaCodigoActividad {
            get {
                return ResourceManager.GetString("EtiquetaCodigoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string EtiquetaCodigoExportado {
            get {
                return ResourceManager.GetString("EtiquetaCodigoExportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Parámetro.
        /// </summary>
        public static string EtiquetaCodigoParametro {
            get {
                return ResourceManager.GetString("EtiquetaCodigoParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Tabla.
        /// </summary>
        public static string EtiquetaCodigoTabla {
            get {
                return ResourceManager.GetString("EtiquetaCodigoTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edición del Control Compensatorio por Solicitud.
        /// </summary>
        public static string EtiquetaCompensatoryControlRequestEditTitle {
            get {
                return ResourceManager.GetString("EtiquetaCompensatoryControlRequestEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Control Compensatorio por Solicitud.
        /// </summary>
        public static string EtiquetaCompensatoryControlRequestTitle {
            get {
                return ResourceManager.GetString("EtiquetaCompensatoryControlRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de Conflictos.
        /// </summary>
        public static string EtiquetaConsultaConflictos {
            get {
                return ResourceManager.GetString("EtiquetaConsultaConflictos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de Transacciones.
        /// </summary>
        public static string EtiquetaConsultaTransacciones {
            get {
                return ResourceManager.GetString("EtiquetaConsultaTransacciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string EtiquetaControl {
            get {
                return ResourceManager.GetString("EtiquetaControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string EtiquetaControlCodigo {
            get {
                return ResourceManager.GetString("EtiquetaControlCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Compensatorio por Solicitud.
        /// </summary>
        public static string EtiquetaControlCompensatorioSolicitud {
            get {
                return ResourceManager.GetString("EtiquetaControlCompensatorioSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string EtiquetaControlDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaControlDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nuevo Control.
        /// </summary>
        public static string EtiquetaControlNew {
            get {
                return ResourceManager.GetString("EtiquetaControlNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Control.
        /// </summary>
        public static string EtiquetaControlNombre {
            get {
                return ResourceManager.GetString("EtiquetaControlNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string EtiquetaControlSistema {
            get {
                return ResourceManager.GetString("EtiquetaControlSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Control.
        /// </summary>
        public static string EtiquetaControlTitle {
            get {
                return ResourceManager.GetString("EtiquetaControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° DOC. IDENTIDAD.
        /// </summary>
        public static string etiquetaDocIdentidad {
            get {
                return ResourceManager.GetString("etiquetaDocIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Parámetros del Sistema.
        /// </summary>
        public static string EtiquetaEditarParamSistema {
            get {
                return ResourceManager.GetString("EtiquetaEditarParamSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proceso.
        /// </summary>
        public static string EtiquetaEditarProceso {
            get {
                return ResourceManager.GetString("EtiquetaEditarProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proceso por Puesto.
        /// </summary>
        public static string EtiquetaEditarProcesoPosition {
            get {
                return ResourceManager.GetString("EtiquetaEditarProcesoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar SubProceso.
        /// </summary>
        public static string EtiquetaEditarSubProceso {
            get {
                return ResourceManager.GetString("EtiquetaEditarSubProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string EtiquetaEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siglas.
        /// </summary>
        public static string EtiquetaEmpresaSiglas {
            get {
                return ResourceManager.GetString("EtiquetaEmpresaSiglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de eliminar Parametro del Sistema.
        /// </summary>
        public static string EtiquetaEstaSeguroEliminarParametro {
            get {
                return ResourceManager.GetString("EtiquetaEstaSeguroEliminarParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Excel.
        /// </summary>
        public static string EtiquetaExpotaExcel {
            get {
                return ResourceManager.GetString("EtiquetaExpotaExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Creación.
        /// </summary>
        public static string EtiquetaFechaCreacion {
            get {
                return ResourceManager.GetString("EtiquetaFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Función.
        /// </summary>
        public static string EtiquetaFuncion {
            get {
                return ResourceManager.GetString("EtiquetaFuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID          :    Auto.
        /// </summary>
        public static string EtiquetaIDAutomatico {
            get {
                return ResourceManager.GetString("EtiquetaIDAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string EtiquetaLimpiar {
            get {
                return ResourceManager.GetString("EtiquetaLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Parámetros del Sistema.
        /// </summary>
        public static string EtiquetaListaParamSistema {
            get {
                return ResourceManager.GetString("EtiquetaListaParamSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Maestras.
        /// </summary>
        public static string EtiquetaMasterCriticalActvity {
            get {
                return ResourceManager.GetString("EtiquetaMasterCriticalActvity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOD - Proceso Detectivo.
        /// </summary>
        public static string EtiquetaMenuSOD {
            get {
                return ResourceManager.GetString("EtiquetaMenuSOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string EtiquetaModulo {
            get {
                return ResourceManager.GetString("EtiquetaModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar.
        /// </summary>
        public static string EtiquetaMostrar {
            get {
                return ResourceManager.GetString("EtiquetaMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturaleza.
        /// </summary>
        public static string EtiquetaNaturaleza {
            get {
                return ResourceManager.GetString("EtiquetaNaturaleza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Actividad.
        /// </summary>
        public static string EtiquetaNombreActividad {
            get {
                return ResourceManager.GetString("EtiquetaNombreActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo elemento +.
        /// </summary>
        public static string EtiquetaNuevoElemento {
            get {
                return ResourceManager.GetString("EtiquetaNuevoElemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nuevo Parámetro del Sistema.
        /// </summary>
        public static string EtiquetaNuevoParamSistema {
            get {
                return ResourceManager.GetString("EtiquetaNuevoParamSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string EtiquetaOrden {
            get {
                return ResourceManager.GetString("EtiquetaOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro actualizado correctamente..
        /// </summary>
        public static string EtiquetaParametroActualizado {
            get {
                return ResourceManager.GetString("EtiquetaParametroActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro del Sistema no se pudo eliminar.
        /// </summary>
        public static string EtiquetaParametroEliminadoError {
            get {
                return ResourceManager.GetString("EtiquetaParametroEliminadoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro del Sistema eliminada correctamente.
        /// </summary>
        public static string EtiquetaParametroEliminadoOk {
            get {
                return ResourceManager.GetString("EtiquetaParametroEliminadoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro guardado correctamente..
        /// </summary>
        public static string EtiquetaParametroGuardado {
            get {
                return ResourceManager.GetString("EtiquetaParametroGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros del Sistema.
        /// </summary>
        public static string EtiquetaParametrosSistema {
            get {
                return ResourceManager.GetString("EtiquetaParametrosSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro del Sistema ya existe.
        /// </summary>
        public static string EtiquetaParametroYaExiste {
            get {
                return ResourceManager.GetString("EtiquetaParametroYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificación de periodo.
        /// </summary>
        public static string EtiquetaPeriodAudited {
            get {
                return ResourceManager.GetString("EtiquetaPeriodAudited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificación de periodo por compañía.
        /// </summary>
        public static string EtiquetaPeriodAuditedDetail {
            get {
                return ResourceManager.GetString("EtiquetaPeriodAuditedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo.
        /// </summary>
        public static string etiquetaPeriodo {
            get {
                return ResourceManager.GetString("etiquetaPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo de Cierre.
        /// </summary>
        public static string EtiquetaPeriodoDeCierre {
            get {
                return ResourceManager.GetString("EtiquetaPeriodoDeCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo - Desde.
        /// </summary>
        public static string EtiquetaPeriodoDesde {
            get {
                return ResourceManager.GetString("EtiquetaPeriodoDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo - Hasta.
        /// </summary>
        public static string EtiquetaPeriodoHasta {
            get {
                return ResourceManager.GetString("EtiquetaPeriodoHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso.
        /// </summary>
        public static string EtiquetaProceso {
            get {
                return ResourceManager.GetString("EtiquetaProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Puestos por Procesos.
        /// </summary>
        public static string EtiquetaProcesoPositionTitle {
            get {
                return ResourceManager.GetString("EtiquetaProcesoPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto por proceso.
        /// </summary>
        public static string EtiquetaProcesoPuesto {
            get {
                return ResourceManager.GetString("EtiquetaProcesoPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string EtiquetaProcessCodigo {
            get {
                return ResourceManager.GetString("EtiquetaProcessCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string EtiquetaProcessDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaProcessDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nuevo Proceso.
        /// </summary>
        public static string EtiquetaProcessNew {
            get {
                return ResourceManager.GetString("EtiquetaProcessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string EtiquetaProcessNombre {
            get {
                return ResourceManager.GetString("EtiquetaProcessNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string EtiquetaProcessPositionDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaProcessPositionDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro guardado correctamente.
        /// </summary>
        public static string EtiquetaProcessPositionGuardado {
            get {
                return ResourceManager.GetString("EtiquetaProcessPositionGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nuevo Proceso por Puesto.
        /// </summary>
        public static string EtiquetaProcessPositionNew {
            get {
                return ResourceManager.GetString("EtiquetaProcessPositionNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string EtiquetaProcessPositionPuesto {
            get {
                return ResourceManager.GetString("EtiquetaProcessPositionPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Procesos y Puestos.
        /// </summary>
        public static string EtiquetaProcessPositionTitle {
            get {
                return ResourceManager.GetString("EtiquetaProcessPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso.
        /// </summary>
        public static string EtiquetaProcessSistema {
            get {
                return ResourceManager.GetString("EtiquetaProcessSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Procesos.
        /// </summary>
        public static string EtiquetaProcessTitle {
            get {
                return ResourceManager.GetString("EtiquetaProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes Generados.
        /// </summary>
        public static string EtiquetaReportesExportados {
            get {
                return ResourceManager.GetString("EtiquetaReportesExportados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Actividad Manual.
        /// </summary>
        public static string EtiquetaRespoActvManual {
            get {
                return ResourceManager.GetString("EtiquetaRespoActvManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de Búsqueda.
        /// </summary>
        public static string EtiquetaResultadoBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Actividad Combinada.
        /// </summary>
        public static string EtiquetaSelActivCombinada {
            get {
                return ResourceManager.GetString("EtiquetaSelActivCombinada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Seleccionar).
        /// </summary>
        public static string EtiquetaSeleccionarCombo {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionarCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string EtiquetaSistema {
            get {
                return ResourceManager.GetString("EtiquetaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nuevo SubProceso.
        /// </summary>
        public static string EtiquetaSub_ProcessNew {
            get {
                return ResourceManager.GetString("EtiquetaSub_ProcessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubProceso.
        /// </summary>
        public static string EtiquetaSub_ProcessSistema {
            get {
                return ResourceManager.GetString("EtiquetaSub_ProcessSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Sub Procesos.
        /// </summary>
        public static string EtiquetaSub_ProcessTitle {
            get {
                return ResourceManager.GetString("EtiquetaSub_ProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Proceso.
        /// </summary>
        public static string EtiquetaSubProceso {
            get {
                return ResourceManager.GetString("EtiquetaSubProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción SubProceso.
        /// </summary>
        public static string EtiquetaSubProcessDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaSubProcessDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre SubProceso.
        /// </summary>
        public static string EtiquetaSubProcessNombre {
            get {
                return ResourceManager.GetString("EtiquetaSubProcessNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Proceso.
        /// </summary>
        public static string EtiquetaSubProcessNombreProcess {
            get {
                return ResourceManager.GetString("EtiquetaSubProcessNombreProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Actividad.
        /// </summary>
        public static string EtiquetaTipoActividad {
            get {
                return ResourceManager.GetString("EtiquetaTipoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Actividad Combinada.
        /// </summary>
        public static string EtiquetaTipoActividadCombinada {
            get {
                return ResourceManager.GetString("EtiquetaTipoActividadCombinada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SICA - Sistema de Control de Actividades.
        /// </summary>
        public static string EtiquetaTituloSistema {
            get {
                return ResourceManager.GetString("EtiquetaTituloSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones.
        /// </summary>
        public static string EtiquetaTransacciones {
            get {
                return ResourceManager.GetString("EtiquetaTransacciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestre.
        /// </summary>
        public static string etiquetaTrimestre {
            get {
                return ResourceManager.GetString("etiquetaTrimestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado por.
        /// </summary>
        public static string EtiquetaUsuarioCreacion {
            get {
                return ResourceManager.GetString("EtiquetaUsuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un proceso asociado al puesto seleccionado.
        /// </summary>
        public static string EtiquetaValidaPosition {
            get {
                return ResourceManager.GetString("EtiquetaValidaPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Cadena.
        /// </summary>
        public static string EtiquetaValorCadena {
            get {
                return ResourceManager.GetString("EtiquetaValorCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Número.
        /// </summary>
        public static string EtiquetaValorNumerico {
            get {
                return ResourceManager.GetString("EtiquetaValorNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ASP.NET MVC Application.
        /// </summary>
        public static string FooterLabel {
            get {
                return ResourceManager.GetString("FooterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your logo here.
        /// </summary>
        public static string LogoLabel {
            get {
                return ResourceManager.GetString("LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un periodo asociado al modulo seleccionado!.
        /// </summary>
        public static string msjClosingValidation {
            get {
                return ResourceManager.GetString("msjClosingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Ingrese una fecha correcta.
        /// </summary>
        public static string msjFechaIncorrecta {
            get {
                return ResourceManager.GetString("msjFechaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Ingrese un mes valido.
        /// </summary>
        public static string msjMesIcorrecto {
            get {
                return ResourceManager.GetString("msjMesIcorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El puesto Usuario solicitante / Jefe inmediato superior, debe de ser el único responsable asignado a una Actividad Crítica.
        /// </summary>
        public static string msjUsuarioSolicitante {
            get {
                return ResourceManager.GetString("msjUsuarioSolicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede seleccionar Usuarios y Puesto en la misma actividad Crítica.
        /// </summary>
        public static string msjValidacionUsuario_Puesto {
            get {
                return ResourceManager.GetString("msjValidacionUsuario_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string PortugueseLabel {
            get {
                return ResourceManager.GetString("PortugueseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string SpanishLabel {
            get {
                return ResourceManager.GetString("SpanishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Combinada.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ASP.NET MVC Application.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string VariableWalter {
            get {
                return ResourceManager.GetString("VariableWalter", resourceCulture);
            }
        }
    }
}
